use_frameworks!
target 'CbliteSwiftJsLib_Tests' do
  pod 'CbliteSwiftJsLib', :path => '../'
  pod 'CouchbaseLite-Enterprise', '~> 3.1'
  pod 'CouchbaseLite-Swift-Enterprise', '~> 3.1'
  pod 'Quick', '~> 2.2.0'
  pod 'Nimble', '~> 10.0.0'
end
